In [1]:
import numpy as np
arr=np.array([1,2,3,4])

In [2]:
result = arr**2

In [3]:
result

array([ 1,  4,  9, 16])

In [4]:
#broadcasting
result=arr+10
result

array([11, 12, 13, 14])

In [5]:
arr1=np.array([1,2,3])
arr2=np.array([10,20,30])
result=arr1+arr2

In [6]:
result

array([11, 22, 33])

In [7]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([7,8,9])
arr1+arr2

array([[ 8, 10, 12],
       [11, 13, 15]])

In [8]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
