In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
flat=arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3:6]

array([4, 5, 6])

In [7]:
flat[:5]

array([1, 2, 3, 4, 5])

In [8]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [13]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [15]:
b=flat[3:7]
b

array([4, 5, 6, 7])

In [16]:
b[0]=4444
b

array([4444,    5,    6,    7])

In [17]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [18]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [20]:
b=flat[3:7].copy()
b

array([4444,    5,    6,    7])

In [21]:
b[0]=123
flat
b

array([123,   5,   6,   7])

In [22]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [23]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [25]:
#exercise
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])